FROM tiangolo/meinheld-gunicorn-flask:python3.8
WORKDIR /opt/application/
ENV PYSPARK_MAJOR_PYTHON_VERSION=3
ENV FLASK_APP=main.py
ENV FLASK_ENV=development
ENV FLASK_RUN_HOST=0.0.0.0
RUN apt update && apt install -y default-jdk
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["flask", "run"]