version: "3.9"

networks:
  bdea_network:
    driver: bridge

services:
  web:
    container_name: flask_webapp
    build: ./flask
    ports:
      - "8000:5000"
    volumes:
      - ./flask:/opt/application/
      - ./spark:/opt/application/spark
    networks:
      - bdea_network
    depends_on:
      - "mariadb"
      - "spark"

  mariadb:
    container_name: mariadb
    image: "mariadb:10.8.2-rc-focal"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_DATABASE=data_frequency
    networks:
      - bdea_network

  spark:
    container_name: spark
    build: ./spark
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
      - SPARK_MASTER_PORT=7077
    volumes:
      - ./flask:/opt/application
      - ./spark:/opt/application/spark
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      - bdea_network

  spark-worker:
    build: ./spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark
    restart: always
    volumes:
      - ./flask:/opt/application
      - ./spark:/opt/application/spark
    networks:
      - bdea_network